apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-binding
  namespace: a-team
subjects:
- kind: ServiceAccount
  name: ctf-serviceaccount
  namespace: a-team
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io