apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-action-deployment
  namespace: a-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-action
  template:
    metadata:
      labels:
        app: github-action
    spec:
      serviceAccountName: ctf-serviceaccount
      securityContext:
        runAsUser: 1000
      containers:
      - name: app-container
        image: ghcr.io/k8s-2025-pschoeppner/ctf-client:0.2.0@sha256:8e37055f6d5eb51c5139b33991b9b74453c407edf1649cc881bd29faf294add6
        args: ["-flag=FromTwoPods", "-server=http://ctf-server.ctf-server.svc.cluster.local:8080", "-id=abc"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ID
          name: POD_ID
        volumeMounts:
        - name: ctf-config
          mountPath: /etc/ctf/config
          subPath: config-file
      volumes:
      - name: ctf-config
        configMap:
          name: ctf-configmap