apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: github-action-daemonset
  namespace: a-team
spec:
  selector:
    matchLabels:
      app: github-action
  template:
    metadata:
      labels:
        app: github-action
    spec:
      serviceAccountName: ctf-serviceaccount
      securityContext:
        runAsUser: 1000
      containers:
      - name: app-container
        image: ghcr.io/k8s-2025-pschoeppner/ctf-client:0.2.1
        args: ["-flag=FromEveryNode", "-server=http://ctf-server.ctf-server.svc.cluster.local:8080", "-id=$(POD_ID)"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: ctf-config
          mountPath: /etc/ctf/config
          subPath: config-file
      volumes:
      - name: ctf-config
        configMap:
          name: ctf-configmap