apiVersion: v1
kind: Pod
metadata:
  name: github-action-pod
  namespace: a-team
spec:
  serviceAccountName: ctf-serviceaccount
  containers:
  - name: app-container
    image: ghcr.io/k8s-2025-pschoeppner/ctf-client:0.2.0
    args: ["-flag=ServiceAccount", "-server=http://ctf-server.ctf-server.svc.cluster.local:8080"]
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    volumeMounts:
    - name: ctf-config
      mountPath: /etc/ctf/config
      subPath: config-file
  volumes:
  - name: ctf-config
    configMap:
      name: ctf-configmap
