apiVersion: v1
kind: Pod
metadata:
  name: github-action-pod
  namespace: a-team
spec:
  containers:
  - name: app-container
    image: ghcr.io/k8s-2025-pschoeppner/a-team-client:sha-3fad73b
    args: ["-flag=ConfigMap", "-server=http://ctf-server.ctf-server.svc.cluster.local:8080"]
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    volumeMounts:
    - name: config-volume
      mountPath: /etc/ctf/config
      subPath: config-file
  volumes:
  - name: config-volume
    configMap:
      name: my-config-map
