apiVersion: batch/v1
kind: CronJob
metadata:
  name: github-action-cronjob
  namespace: a-team
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      completions: 2
      parallelism: 1
      template:
        metadata:
          labels:
            app: github-action
        spec:
          restartPolicy: Never
          serviceAccountName: ctf-serviceaccount
          securityContext:
            runAsUser: 1000
          containers:
          - name: app-container
            image: ghcr.io/k8s-2025-pschoeppner/ctf-client:0.2.1
            args: ["-flag=FromOnePodTwice", "-server=http://ctf-server.ctf-server.svc.cluster.local:8080", "-id=maaaaag"]
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            volumeMounts:
            - name: ctf-config
              mountPath: /etc/ctf/config
              subPath: config-file
          volumes:
          - name: ctf-config
            configMap:
              name: ctf-configmap