apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: a-team-pvc-2
  namespace: a-team
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard