apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: a-team-pvc-7
  namespace: a-team
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage